
INSERT INTO workshop.work_order (id, vehicle_id, mechanic_id, problem_description)
VALUES
(1, 1, 5, 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in'),
(2, 1, 5, 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in'),
(3, 5, 1, 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque'),
(4, 3, 4, 'tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet'),
(5, 5, 5, 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec'),
(6, 3, 2, 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam'),
(7, 5, 5, 'nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin'),
(8, 2, 4, 'duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis'),
(9, 2, 2, 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque'),
(10, 2, 3, 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et'),
(11, 2, 5, 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id'),
(12, 4, 2, 'nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque'),
(13, 5, 2, 'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet'),
(14, 5, 1, 'primis in faucibus orci luctus et ultrices posuere cubilia curae'),
(15, 3, 3, 'adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere'),
(16, 1, 4, 'sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis'),
(17, 4, 5, 'nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula'),
(18, 5, 3, 'suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis'),
(19, 5, 3, 'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat'),
(20, 1, 2, 'hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida'),
(21, 1, 4, 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam'),
(22, 3, 3, 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id'),
(23, 4, 1, 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis'),
(24, 3, 5, 'nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in'),
(25, 4, 2, 'in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo'),
(26, 4, 2, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus'),
(27, 1, 2, 'lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum'),
(28, 4, 1, 'ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit'),
(29, 2, 1, 'eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque'),
(30, 2, 4, 'leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat'),
(31, 4, 3, 'ligula nec sem duis aliquam convallis nunc proin at turpis a'),
(32, 5, 2, 'semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero'),
(33, 4, 4, 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt'),
(34, 5, 1, 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent'),
(35, 2, 1, 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget'),
(36, 1, 3, 'cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis'),
(37, 1, 3, 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac'),
(38, 3, 3, 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel'),
(39, 5, 2, 'molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna'),
(40, 3, 3, 'eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse'),
(41, 5, 1, 'id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est'),
(42, 2, 5, 'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend'),
(43, 5, 2, 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer'),
(44, 2, 2, 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus'),
(45, 5, 1, 'mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer'),
(46, 5, 4, 'purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id'),
(47, 1, 1, 'pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue'),
(48, 5, 3, 'nisl nunc rhoncus dui vel sem sed sagittis nam congue'),
(49, 3, 2, 'donec ut mauris eget massa tempor convallis nulla neque libero convallis eget'),
(50, 1, 2, 'praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet');